config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/index'

  resources :members
  resources :events do
    collection do
      get 'search'
    end
  end
    
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates :name, presence: true, length: { minimum: 2 }
    validates :start_time, presence: true
    validates :end_time, presence: true, numericality: { greater_than: :start_time}
    validates :location, presence: true
    #validates :attendance_num, numericality: { only_integer: true }

    searchable do
        text :name
    end
end

app/models/member.rb
class Member < ApplicationRecord
    validates :name, presence: true
    validates :gender, presence: true
    validates :dob, presence: true
    validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
      @events = Event.all
      @search = params["search"]

      if @search.present?
        @name = @search["name"]
        @events = Event.where("name LIKE ?", "%#{@name}%")
        if @events.blank?
          @event_return = "empty"
          # @events = ["No data found"]
        # else
          
        end
      end
    end

    def new
      @screen_mode = "add"
      @event = Event.new
    end

    def show
      @event = Event.find(params[:id])
    end

    def create
      @event = Event.new(event_params)

      if @event.save
        redirect_to @event
      else
        render 'new'
      end 
    end

    def edit
      @screen_mode = "edit"
      @event = Event.find(params[:id])
    end

    def update
      @event = Event.find(params[:id])

      if @event.update(event_params)
        redirect_to @event
      else
        render 'edit'
      end
    end

    def destroy
      @event = Event.find(params[:id])
      @event.destroy

      redirect_to events_path
    end

    private
    def event_params
      params.require(:event).permit(:name, :start_time, :end_time, :location, :description)
    end

    # def search_params
    #   params.require(:event).permit(:name)
    # end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
    def index
      @members = Member.all

      @search = params["search"]
      if @search.present?
        @name = @search["name"]
        @members = Member.where("name LIKE ?", "%#{@name}%")
        if @members.blank?
          @member_return = "empty"
        # elsif @name.present? == 'true'
        # else
        #   @members
        end
      end
    end

    def show
      @member = Member.find(params[:id])
    end

    def new
      @member = Member.new
    end

    def create
      @member = Member.new(member_params)

      if @member.save
        redirect_to @member
      else
        render 'new' ##use render to pass the values back
      end
    end

    def edit
      @member = Member.find(params[:id])
    end

    def update
      @member = Member.find(params[:id])

      if @member.update(member_params)
        redirect_to @member
      else
        render 'edit'
      end
    end
    
    def destroy
      @member = Member.find(params[:id])
      @member.destroy

      redirect_to members_path
    end

    private
    def member_params
      params.require(:member).permit(:name, :gender, :dob, :status, :occupation, :phone, :email, :instagram, :line, :address)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
<% if @screen_mode == 'edit' %>
    <%= f.input :name, label: "Name:", readonly: true %>
<% else %>
     <%= f.input :name, label: "Name:" %>
<% end %>
<%= f.input :start_time, label: "Start Time:" %>
<%= f.input :end_time, label: "End Time:" %>
<%= f.input :location, label: "Location:" %>
<%= f.input :description, label: "Description:" %>
<%= f.button :button, "Reset", :type => 'reset', class: "btn btn-secondary" %>
<%= f.button :submit, "Save", class: "btn btn-primary" %>
<% end %>

app/views/events/_search.html.erb
<%= simple_form_for :search, url: events_path, method: "GET", html: {class: "form-inline"} do |f| %>
<div class="row">
    <div class="col-2" style="padding-top: 5px;">
        Name: 
    </div>
    <div class="col-7">
        <%= f.input :name, required: false, label: false, input_html: {value: ""} %>
    </div>
    <div class="col-3">
        <%= f.button :button, class: "btn btn-primary" do %>
            <i class="fas fa-search"></i>
        <% end %>
    </div>
</div>
<% end %>

app/views/events/edit.html.erb
<%= render  'layouts/header' %>
<div class="container border rounded rounded-sm" style="width: 35%; margin-top: 15px;">
    <div style="margin-top: 10px; margin-left: 0px;">
        <h4>Edit Event</h4>
        <%= render 'form' %>
    </div>
</div>

app/views/events/index.html.erb
<%= render 'layouts/header' %>

<div class="container-fluid">
    <div class="row">
        <div class="col-3" style="padding-top: 15px;">
            <%= render 'search' %>
        </div>
    </div>
    <div class="row">
        <div class="col-12" style="padding-top: 15px;">
            <%= link_to new_event_path, class:"btn btn-primary" do %><i class="fas fa-plus"></i><% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-12" style="padding-left: 15px; padding-right: 15px; padding-top: 10px;">
            <table class="table table-striped table-hover table-bordered table-sm">
                <thead class="thead-light">
                    <tr>
                        <th scope="col" style="width: 30px;" class="text-center">No.</th>
                        <th scope="col" style="width: 200px;">Event's Name</th>
                        <th scope="col" style="width: 100px;">Date</th>
                        <th scope="col" style="width: 100px;">Time</th>
                        <th scope="col" style="width: 200px;">Location</th>
                        <th scope="col" style="width: 80px;">Total Attendees</th>
                        <th scope="col" style="width: 5px;">Action</th>
                    </tr>
                </thead>
                <% if @event_return == "empty" %>
                    <tbody>
                        <tr>
                            <td colspan="7"><b>No data found.</b></td>
                        </tr>
                    </tbody>
                <% else %>
                    <tbody>
                    <% a = 1 %>
                    <% @events.each do |e| %>
                        <tr>
                            <td class="text-center"><%= a %></td>
                            <td><%= link_to  event_path(e), class:"text-decoration-none text-capitalize" do %><%= e.name %> <% end %></td>
                            <td><%= e.start_time.strftime('%d-%m-%Y') %> - <%= e.end_time.strftime('%d-%m-%Y') %></td>
                            <td><%= e.start_time.strftime('%H.%M') %> - <%= e.end_time.strftime('%H.%M') %></td>
                            <td><%= e.location %></td>
                            <td><%= e.attendance_num %></td>
                            <td><%= link_to edit_event_path(e), class:"btn btn-secondary btn-sm"  do %>
                                        <i class="fas fa-edit"></i> 
                                    <% end %>
                                    <%= link_to event_path(e), method: :delete, data: { confirm: 'Are you sure?'},
                                        class:"btn btn-secondary btn-sm" do %>
                                        <i class="fas fa-trash"></i>
                                    <% end %>
                            </td>
                        </tr>
                    <% end %>
                    </tbody>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/events/new.html.erb
<%= render 'layouts/header' %>

<div class="container border rounded rounded-sm" style="width: 35%; margin-top: 15px;">
    <div style="margin-top: 10px; margin-left: 0px; padding: 5px;">
        <h4>Add new Event</h4>
        <%= render 'form' %>
    </div>
</div>

app/views/events/show.html.erb
<%= render 'layouts/header' %>

<div class="container justify-content-center" style="margin-top: 10px; padding: 10px; width: 50%;">
    <div class="row">
        <div class="col-12">
            <h4>
                <b><%= @event.name %></b>
            </h4>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            Start Time
        </div>
        <div class="col-10">
            : <%= @event.start_time.strftime('%d-%b-%Y %H.%M %:z') %>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            End Time
        </div>
        <div class="col-10">
            : <%= @event.end_time.strftime('%d-%b-%Y %H.%M %:z') %>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            Location
        </div>
        <div class="col-10">
            : <%= @event.location %>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            Description
        </div>
        <div class="col-10">
            : <%= @event.description %>
        </div>
    </div>
    <div class="row" style="padding-top: 10px;">
        <div class="col-10">
            <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#modalEvent">See Attended Events</button>
        </div>
        <div class="col-2" style="padding-left: 50px;">
            <%= link_to "Back", events_path, class:"btn btn-outline-secondary" %>
        </div>
    </div>
    <div class="modal fade" id="modalEvent" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="modal-title">
                        <h4>Attendants</h4>
                    </div>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                   Dolorem ipsum. 
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <%= link_to welcome_index_path, class: "navbar-brand" do %>
      <b style='font-family: "Trebuchet MS", Helvetica, sans-serif'>EAA</b>
  <% end %>
    <div class="collapse navbar-collapse">
      <div class="navbar-nav">
        <%= link_to 'Members', members_path, class: "nav-item nav-link active" %> 
        <%= link_to "Events", {controller: 'events'}, class: "nav-item nav-link active" %>
      </div>
    </div>
    <div class="collapse navbar-collapse float-right" style="margin-left: 77%;">
      <ul class="navbar-nav">
        <li class="nav-item nav-link active">
          Login
        </li>
        <li class="nav-item nav-link active">
          Register
        </li>
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Attendance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= simple_form_for @member do |f| %>
<%= f.input :name, label: "Full Name: " %>
<%= f.input :gender, label: "Gender: ", as: :select, 
    collection: [['Male', 'Male'], ['Female', 'Female'], ['Others', 'Others']] %>
<%= f.input :dob, label: "Date of Birth: ", start_year: Date.today.year - 150, end_year: Date.today.year %>
<%= f.input :status, label: "Status: ", as: :select, 
    collection: [['Unmarried', 'Unmarried'], ['Married', 'Married'], ['Divorced', 'Divorced'], 
    ['Widow/Widower', 'Widow/Widower']], class: "form-control" %>
<%= f.input :occupation, label: "Occupation: ", as: :select, 
    collection: [['Student', 'Student'], ['College/University Student', 'College/University Student'], 
    ['Freelancer', 'Freelancer'], ['Government Employee', 'Government Employee'], ['Private Employee', 'Private Employee'], 
    ['Entrepeneur', 'Entrepeneur'], ['Others', 'Others']] %>
<%= f.input :phone, label: "Phone Number: ", error: "Phone must be filled with number", hint: "Must be filled with number.", as: :integer,
    input_html: { onkeydown: "phoneNumCheck(event)" } %>
<%= f.input :email, label: "Email: ", hint: "Mail must be valid! Example: user@mail.com" %>
<%= f.input :instagram, label: "Instagram: " %>
<%= f.input :line, label: "Line: " %>
<%= f.input :address, label: "Address: " %>
<%= f.button :button, "Reset", :type => 'reset', class: "btn btn-secondary" %>
<%= f.button :submit, "Save", class: "btn btn-primary" %>
<% end %>

app/views/members/_search.html.erb
<%= simple_form_for :search, url: members_path, method: "GET", html: {class: "form-inline"} do |f| %>
<div class="row">
    <div class="col-2" style="padding-top: 5px;">
        Name: 
    </div>
    <div class="col-7">
        <%= f.input :name, required: false, label: false, input_html: {value: ""} %>
    </div>
    <div class="col-3">
        <%= f.button :button, class: "btn btn-primary" do %>
            <i class="fas fa-search"></i>
        <% end %>
    </div>
</div>
<% end %>

app/views/members/edit.html.erb
<%= render  'layouts/header' %>
<div class="container border rounded rounded-sm" style="width: 35%; margin-top: 15px;">
    <div style="margin-top: 10px; margin-left: 0px;">
        <h4>Edit Member</h4>
        <%= render 'form' %>
    </div>
</div>

app/views/members/index.html.erb
<%= render 'layouts/header' %>

<div class="container-fluid">
    <div class="row">
        <div class="col-3" style="padding-top: 15px;">
            <%= render 'search' %>
        </div>
    </div>

    <div class="row">
        <div class="col-12" style="padding-top: 15px;">
            <%= link_to new_member_path, class:"btn btn-primary" do %><i class="fas fa-plus"></i><% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-12" style="padding-left: 30px; padding-right: 30px; padding-top: 15px;">
            <table class="table table-striped table-hover table-bordered table-sm">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col" style="width: 10px;" class="text-center">No.</th>
                        <th scope="col" style="width: 200px;">Name</th>
                        <th scope="col" style="width: 100px;">Gender</th>
                        <th scope="col" style="width: 150px;">Date of Birth</th>
                        <th scope="col" style="width: 100px;">Created At</th>
                        <th scope="col" style="width: 100px;">Updated At</th>
                        <th scope="col" style="width: 50px;">Action</th>
                    </tr>
                </thead>
                <% if @member_return == "empty" %>
                    <tbody>
                        <tr>
                            <td colspan="7">
                                <b>No data found.</b>
                            </td>
                        </tr>
                    </tbody>
                <% else %>
                    <tbody>
                        <% a = 1 %>
                        <% @members.each do |m| %>
                            <tr>
                                <td class="text-center"><%= a %></td>
                                <td class="text-capitalize"><%= link_to member_path(m), class:"text-decoration-none" do %><%= m.name %><% end %></td>
                                <td><%= m.gender %></td>
                                <td><%= m.dob.strftime('%d-%B-%Y') %></td>
                                <td><%= m.created_at.strftime('%d-%m-%Y %H.%M.%S') %></td>
                                <td><%= m.updated_at.strftime('%d-%m-%Y %H.%M.%S') %></td>
                                <td><%= link_to edit_member_path(m), class:"btn btn-secondary btn-sm"  do %>
                                        <i class="fas fa-edit"></i> 
                                    <% end %>
                                    <%= link_to member_path(m), method: :delete, data: { confirm: 'Are you sure?'},
                                        class:"btn btn-secondary btn-sm" do %>
                                        <i class="fas fa-user-minus"></i>
                                    <% end %>
                                </td>
                            </tr>
                            <% a+=1 %>
                        <% end %>
                    </tbody>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/members/new.html.erb
<%= render 'layouts/header' %>

<div class="container border rounded rounded-sm" style="width: 35%; margin-top: 15px;">
    <div style="margin-top: 10px; margin-left: 0px;">
        <h4>Add new Member</h4>
        <%= render 'form' %>
    </div>
</div>

app/views/members/show.html.erb
<%= render  "layouts/header" %>
<div class="container justify-content-center" style="margin-top: 10px; padding: 10px; width: 50%;">
    <div class="row">
        <div class="col-12">
            <h4 class="display-4"><b><%= @member.name %></b></h6>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            Gender
        </div>
        <div class="col-10">
            : <%= @member.gender %>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            Date of Birth 
        </div>
        <div class="col-10">
            : <%= @member.dob.strftime('%d-%m-%Y') %> 
            <small class="text-muted">(dd-mm-yyyy)</small>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            Status
        </div>
        <div class="col-10">
            : <%= @member.status %>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            Occupation
        </div>
        <div class="col-10">
            : <%= @member.occupation %>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            Phone
        </div>
        <div class="col-10">
            : <%= @member.phone %>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            Email
        </div>
        <div class="col-10">
            : <%= @member.email %>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            Instagram
        </div>
        <div class="col-10">
            : <%= @member.instagram %>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            Line
        </div>
        <div class="col-10">
            : <%= @member.line %>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            Address
        </div>
        <div class="col-10">
            : <%= @member.address %>
        </div>
    </div>
    <div class="row" style="padding-top: 10px;">
        <div class="col-10">
            <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#modalMember">See Attended Events</button>
        </div>
        <div class="col-2" style="padding-left: 50px;">
            <%= link_to "Back", members_path, class:"btn btn-outline-secondary" %>
        </div>
    </div>
    <div class="modal fade" id="modalMember" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="modal-title">
                        <h4>Events Attended</h4>
                    </div>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                   Dolorem ipsum. 
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/welcome/index.html.erb
<div>
<%= render 'layouts/header' %>
</div>